apiVersion: v1
kind: ImageStream
metadata:
    name: postgres
spec:
    tags:
    - from:
          kind: DockerImage
          name: postgres
      name: latest
      importPolicy:
          scheduled: true
