apiVersion: v1
kind: Service
metadata:
  name: receiver
  lables:
    app: receiver
spec:
  selector:
    app: receiver
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver
  labels:
    app: receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: receiver
        version: v1
    spec:
      containers:
      - name: receiver
        image: docker-registry.default.svc:5000/nemo/receiver:0.1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        ports:
        - containerPort: 8080