kind: Service
apiVersion: v1
metadata:
  name: mongo-likes
spec:
  selector:
    app: mongo-likes
  ports:
  - name: mongo
    port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-likes
  labels:
    app: mongo-likes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-likes
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: mongo-likes
    spec:
      containers:
      - name: mongo-likes
        image: docker-registry.default.svc:5000/nemo/mongo:latest
        ports:
        - containerPort: 27017