apiVersion: v1
kind: ImageStream
metadata:
    name: comments
spec:
    tags:
    - from:
          kind: DockerImage
          name: docker-registry.default.svc:5000/nemo/comments
      name: latest
      importPolicy:
          scheduled: true
