kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "comments"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/Dimss/nemo-comments.git"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "python-36-rhel7:latest"
  output:
    to:
      kind: "ImageStreamTag"
      name: "comments:0.1"
