apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-new-version
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: identity
        version: v2
    spec:
      containers:
      - name: identity
        image: docker-registry.default.svc:5000/nemo/identity-new-version:0.1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        ports:
        - containerPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: identity
spec:
  host: identity
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: identity
spec:
  hosts:
    - identity.nemo
    - identity
  gateways:
  - nemo-gateway
  http:
  - match:
    - headers:
        X-APP-TEST:
          exact: test
    route:
    - destination:
        host: identity
        subset: v2
  - route:
    - destination:
        host: identity
        subset: v1
      weight: 100
    corsPolicy:
      allowOrigin:
        - "*"
      allowMethods:
        - POST
        - GET
        - DELETE
        - PUT
        - OPTIONS
      allowHeaders:
        - "X-NEMO-AUTH"
        - "Origin"
        - "Accept"
        - "Content-Type"
        - "Authorization"
      exposeHeaders:
        - x-custom-header
      maxAge: 300s
      allowCredentials: true