kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "links"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/Dimss/nemo-links.git"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "nodejs-8-rhel7:latest"
  output:
    to:
      kind: "ImageStreamTag"
      name: "links:0.1"
