apiVersion: v1
kind: ImageStream
metadata:
    name: python-36-rhel7
spec:
    tags:
    - from:
          kind: DockerImage
          name: registry.access.redhat.com/rhscl/python-36-rhel7
      name: latest
      importPolicy:
          scheduled: true
