# kind: Service
# apiVersion: v1
# metadata:
#   name: tel
#   lables:
#     app: tel
# spec:
#   selector:
#     app: tel
#   ports:
#   - name: http
#     port: 8022
#     targetPort: 8022
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: DestinationRule
# metadata:
#   name: tel
# spec:
#   host: tel
#   trafficPolicy:
#     tls:
#       mode: ISTIO_MUTUAL

---
apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  name: tel
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: tel
    spec:
      containers:
      - name: tel
        image: datawire/telepresence-k8s:0.95
        # ports:
        # - containerPort: 8022
  replicas: 1
  triggers:
  - type: ConfigChange
  strategy:
    type: Rolling
  paused: false
  revisionHistoryLimit: 2
  minReadySeconds: 0