kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "ui"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/Dimss/nemo-ui.git"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "nodejs-8-rhel7:latest"
  output:
    to:
      kind: "ImageStreamTag"
      name: "ui:0.1"
