apiVersion: v1
kind: ImageStream
metadata:
    name: identity
spec:
    tags:
    - from:
          kind: DockerImage
          name: docker-registry.default.svc:5000/nemo/identity
      name: latest
      importPolicy:
          scheduled: true
---
apiVersion: v1
kind: ImageStream
metadata:
    name: identity-new-version
spec:
    tags:
    - from:
          kind: DockerImage
          name: docker-registry.default.svc:5000/nemo/identity-new-version
      name: latest
      importPolicy:
          scheduled: true
