kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "identity"
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/Dimss/nemo-identity-service.git"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "openjdk18-openshift:latest"
  output:
    to:
      kind: "ImageStreamTag"
      name: "identity:0.1"
