kind: Service
apiVersion: v1
metadata:
  name: identity
  lables:
    app: identity
spec:
  selector:
    app: identity
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: identity
        version: v1
    spec:
      containers:
      - name: identity
        image: docker-registry.default.svc:5000/nemo/identity:0.1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        ports:
        - containerPort: 8080