kind: Service
apiVersion: v1
metadata:
  name: feed
  lables:
    app: feed
spec:
  selector:
    app: feed
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed
  labels:
    app: feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: feed
        version: v1
    spec:
      containers:
      - name: feed
        image: docker-registry.default.svc:5000/nemo/feed:0.1
        # imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: "JAVA_APP_JAR"
          value: "feed-0.7-fat.jar"
        ports:
        - containerPort: 8080