apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: likes-delay-drule
spec:
  host: likes
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: likes-delay-vs
spec:
  hosts:
    - likes
  http:
  - fault:
      delay:
        fixedDelay: 10s
        percent: 100
    match:
    - headers:
        X-APP-TEST:
          exact: test
    route:
    - destination:
        host: likes
        subset: v1
  - route:
    - destination:
        host: likes
        subset: v1