apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: feed
spec:
  host: feed
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v1d
    labels:
      version: v1d
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: feed
spec:
  hosts:
    - feed.nemo
    - feed
  gateways:
  - nemo-gateway
  http:
  - route:
    - destination:
        host: feed
        subset: v1
      weight: 100
    mirror:
      host: feed
      subset: v1d
    corsPolicy:
      allowOrigin:
        - "*"
      allowMethods:
        - POST
        - GET
        - DELETE
        - PUT
        - OPTIONS
      allowHeaders:
        - "X-NEMO-AUTH"
        - "Origin"
        - "Accept"
        - "Content-Type"
        - "Authorization"
      exposeHeaders:
        - x-custom-header
      maxAge: 300s
      allowCredentials: true